from model import *

tables = [Player, Fight, Inventory, ItemType, ItemOrigin, Descriptor, Event, Penalty]
for table in tables:
   if not table.table_exists():
      table.create_table()
      if table is ItemOrigin:
         #Create ItemOrigin
         ItemOrigin.create(name="Paper",            stat=1,  req_level=-1, fightable=False)
         ItemOrigin.create(name="Cloth",            stat=1,  req_level=-1, fightable=False)
         ItemOrigin.create(name="Leather",          stat=2,  req_level=-1,  fightable=False)
         ItemOrigin.create(name="Wooden",           stat=3,  req_level=-1,  fightable=False)
         ItemOrigin.create(name="Dark Wood",        stat=4, req_level=4, fightable=False)
         ItemOrigin.create(name="Stone",            stat=6,  req_level=6,  fightable=False)
         ItemOrigin.create(name="Granite",          stat=8,  req_level=8,  fightable=False)
         ItemOrigin.create(name="Gold",             stat=10,  req_level=10,  fightable=False)
         ItemOrigin.create(name="Bronze",           stat=14,  req_level=14,  fightable=False)
         ItemOrigin.create(name="Iron",             stat=16,  req_level=16,  fightable=False)
         ItemOrigin.create(name="Steel",            stat=18, req_level=18, fightable=False)
         ItemOrigin.create(name="Mithril",          stat=20, req_level=20, fightable=False)
         ItemOrigin.create(name="Platinum",         stat=24, req_level=24, fightable=False)
         ItemOrigin.create(name="Hastur",           stat=26, req_level=26, fightable=True)
         ItemOrigin.create(name="Ithaqua",          stat=28, req_level=28, fightable=True)
         ItemOrigin.create(name="Nyarlathotep",     stat=30, req_level=30, fightable=True)
         ItemOrigin.create(name="Zhar and Lloigor", stat=34, req_level=34, fightable=True)
         ItemOrigin.create(name="Cyaegha",          stat=36, req_level=36, fightable=True)
         ItemOrigin.create(name="Nyogtha",          stat=38, req_level=38, fightable=True)
         ItemOrigin.create(name="Shub-Nuggurath",   stat=40, req_level=40, fightable=True)
         ItemOrigin.create(name="Tsathoggua",       stat=44, req_level=44, fightable=True)
         ItemOrigin.create(name="Aphoom-Zhah",      stat=46, req_level=46, fightable=True)
         ItemOrigin.create(name="Cthugha",          stat=48, req_level=48, fightable=True)
         ItemOrigin.create(name="Dagon",            stat=50, req_level=50, fightable=True)
         ItemOrigin.create(name="Ghatanothoa",      stat=54, req_level=54, fightable=True)
         ItemOrigin.create(name="Mother Hydra",     stat=56, req_level=56, fightable=True)
         ItemOrigin.create(name="Zoth-Ommog",       stat=58, req_level=58, fightable=True)
         ItemOrigin.create(name="Cthulhu",          stat=60, req_level=60, fightable=True)
      elif table is ItemType:
         #Create ItemTypes
         ItemType.create(name="Shoes",        stat=1, req_level=-1)
         ItemType.create(name="Armet",        stat=2, req_level=-1)
         ItemType.create(name="Cape",         stat=3, req_level=-1)
         ItemType.create(name="Pants",        stat=1, req_level=-1)
         ItemType.create(name="Sword",        stat=2, req_level=-1)
         ItemType.create(name="Shield",       stat=3, req_level=-1)
         ItemType.create(name="Gauntlets",    stat=1, req_level=-1)
         ItemType.create(name="Belt",         stat=2, req_level=-1)
         ItemType.create(name="Glasses",      stat=3, req_level=-1)
         ItemType.create(name="Undergarmets", stat=1, req_level=-1)
         ItemType.create(name="Pauldron",     stat=2, req_level=-1)
         ItemType.create(name="Bevor",        stat=3, req_level=-1)
         ItemType.create(name="Bow",          stat=1, req_level=-1)
         ItemType.create(name="Chainmail",    stat=2, req_level=-1)
         ItemType.create(name="Ring",         stat=3, req_level=-1)
      elif table is Descriptor:
         #Create Descriptors
         Descriptor.create(name="The Novice",  stat=1,  req_level=-1)
         Descriptor.create(name="The Bitter",  stat=1,  req_level=1)
         Descriptor.create(name="Wrath",       stat=1, req_level=2)
         Descriptor.create(name="The Mighty",  stat=1,  req_level=3)
         Descriptor.create(name="The Weak",    stat=-1, req_level=4)
         Descriptor.create(name="Pride",       stat=1,  req_level=5)
         Descriptor.create(name="Swiftness",   stat=2,  req_level=6)
         Descriptor.create(name="Slowness",    stat=-2, req_level=9)
         Descriptor.create(name="Fear",        stat=2, req_level=12)
         Descriptor.create(name="Courage",     stat=2,  req_level=15)
         Descriptor.create(name="Strength",    stat=3,  req_level=18)
         Descriptor.create(name="Power",       stat=3,  req_level=21)
         Descriptor.create(name="Sloth",       stat=4, req_level=24)
         Descriptor.create(name="Weakness",    stat=-4, req_level=27)
         Descriptor.create(name="Gluttony",    stat=-5, req_level=30)
         Descriptor.create(name="Trust",       stat=5,  req_level=33)
         Descriptor.create(name="Greed",       stat=-6, req_level=36)
         Descriptor.create(name="Shame",       stat=6, req_level=39)
         Descriptor.create(name="Envy",        stat=7, req_level=42)
         Descriptor.create(name="Good Luck",   stat=8,  req_level=45)
         Descriptor.create(name="Bad Luck",    stat=-9, req_level=48)
         Descriptor.create(name="Lust",        stat=10, req_level=51)
         Descriptor.create(name="Zen",         stat=11,  req_level=54)
         Descriptor.create(name="Will",        stat=12,  req_level=57)
         Descriptor.create(name="The Hero",    stat=15,  req_level=60)