from model import *

tables = [Player, Fight, Inventory, ItemType, ItemOrigin, Descriptor]
for table in tables:
   if not table.table_exists():
      table.create_table()

#Create ItemOrigin
ItemOrigin.create(name="Cloth",            stat=1,  req_level=-1, fightable=False)
ItemOrigin.create(name="Wooden",           stat=2,  req_level=1,  fightable=False)
ItemOrigin.create(name="Leather",          stat=3,  req_level=2,  fightable=False)
ItemOrigin.create(name="Stone",            stat=3,  req_level=2,  fightable=False)
ItemOrigin.create(name="Gold",             stat=4,  req_level=4,  fightable=False)
ItemOrigin.create(name="Granite",          stat=5,  req_level=5,  fightable=False)
ItemOrigin.create(name="Bronze",           stat=7,  req_level=7,  fightable=False)
ItemOrigin.create(name="Iron",             stat=8,  req_level=8,  fightable=False)
ItemOrigin.create(name="Steel",            stat=10, req_level=10, fightable=False)
ItemOrigin.create(name="Hastur",           stat=11, req_level=11, fightable=True)
ItemOrigin.create(name="Ithaqua",          stat=12, req_level=12, fightable=True)
ItemOrigin.create(name="Nyarlathotep",     stat=17, req_level=17, fightable=True)
ItemOrigin.create(name="Zhar and Lloigor", stat=20, req_level=20, fightable=True)
ItemOrigin.create(name="Cyaegha",          stat=23, req_level=23, fightable=True)
ItemOrigin.create(name="Nyogtha",          stat=28, req_level=28, fightable=True)
ItemOrigin.create(name="Shub-Nuggurath",   stat=31, req_level=31, fightable=True)
ItemOrigin.create(name="Tsathoggua",       stat=34, req_level=34, fightable=True)
ItemOrigin.create(name="Aphoom-Zhah",      stat=39, req_level=39, fightable=True)
ItemOrigin.create(name="Cthugha",          stat=42, req_level=42, fightable=True)
ItemOrigin.create(name="Dagon",            stat=45, req_level=45, fightable=True)
ItemOrigin.create(name="Ghatanothoa",      stat=50, req_level=50, fightable=True)
ItemOrigin.create(name="Mother Hydra",     stat=53, req_level=53, fightable=True)
ItemOrigin.create(name="Zoth-Ommog",       stat=56, req_level=56, fightable=True)
ItemOrigin.create(name="Cthulhu",          stat=61, req_level=61, fightable=True)

#Create ItemTypes
ItemType.create(name="Shoes",        stat=1, req_level=-1)
ItemType.create(name="Armet",        stat=2, req_level=-1)
ItemType.create(name="Cape",         stat=3, req_level=-1)
ItemType.create(name="Pants",        stat=1, req_level=-1)
ItemType.create(name="Sword",        stat=2, req_level=-1)
ItemType.create(name="Shield",       stat=3, req_level=-1)
ItemType.create(name="Gauntlets",    stat=1, req_level=-1)
ItemType.create(name="Belt",         stat=2, req_level=-1)
ItemType.create(name="Glasses",      stat=3, req_level=-1)
ItemType.create(name="Undergarmets", stat=1, req_level=-1)
ItemType.create(name="Pauldron",     stat=2, req_level=-1)
ItemType.create(name="Bevor",        stat=3, req_level=-1)
ItemType.create(name="Bow",          stat=1, req_level=-1)
ItemType.create(name="Chainmail",    stat=2, req_level=-1)
ItemType.create(name="Ring",         stat=3, req_level=-1)

#Create Descriptors
Descriptor.create(name="The Noob",    stat=1,  req_level=-1)
Descriptor.create(name="The Novice",  stat=1,  req_level=1)
Descriptor.create(name="Hell",        stat=1,  req_level=2)
Descriptor.create(name="Heaven",      stat=1,  req_level=2)
Descriptor.create(name="The Bitter",  stat=1,  req_level=4)
Descriptor.create(name="The Mighty",  stat=2,  req_level=8)
Descriptor.create(name="The Weak",    stat=-2, req_level=8)
Descriptor.create(name="Swiftness",   stat=2,  req_level=16)
Descriptor.create(name="Slowness",    stat=-2, req_level=16)
Descriptor.create(name="The Hero",    stat=3,  req_level=24)
Descriptor.create(name="The Jester",  stat=-3, req_level=24)
Descriptor.create(name="Fear",        stat=-4, req_level=32)
Descriptor.create(name="Courage",     stat=4,  req_level=32)
Descriptor.create(name="Strength",    stat=4,  req_level=37)
Descriptor.create(name="Power",       stat=5,  req_level=40)
Descriptor.create(name="Weakness",    stat=-5, req_level=40)
Descriptor.create(name="Trust",       stat=5,  req_level=43)
Descriptor.create(name="Forgiveness", stat=5,  req_level=43)
Descriptor.create(name="Pride",       stat=5,  req_level=51)
Descriptor.create(name="Shame",       stat=-5, req_level=51)
Descriptor.create(name="Good Luck",   stat=6,  req_level=59)
Descriptor.create(name="Bad Luck",    stat=-6, req_level=59)